name: Make Custom Test Log
description: Build a human-readable test+coverage log file for persistence
inputs:
  repo:
    required: true
  commit_sha:
    required: true
  run_id:
    required: true
  run_number:
    required: true
outputs:
  log-path:
    description: "Path to the created log file"
    value: ${{ steps.make.outputs.log_path }}
runs:
  using: "composite"
  steps:
    - name: Ensure jq is available (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y jq
    - id: make
      name: Build custom test log
      shell: bash
      run: |
        set -euo pipefail
        LOG_PATH="custom-test-log.txt"
        echo "Commit: ${{ inputs.commit_sha }}"           >  "$LOG_PATH"
        echo "Repo:   ${{ inputs.repo }}"                 >> "$LOG_PATH"
        echo "Run:    #${{ inputs.run_number }} (id ${{ inputs.run_id }})" >> "$LOG_PATH"
        echo "When:   $(date -u +'%Y-%m-%dT%H:%M:%SZ') (UTC)" >> "$LOG_PATH"
        echo "" >> "$LOG_PATH"
        if [ -f "backend/reports/jest-results.json" ]; then
          TOTAL=$(jq '.numTotalTests' backend/reports/jest-results.json)
          PASSED=$(jq '.numPassedTests' backend/reports/jest-results.json)
          FAILED=$(jq '.numFailedTests' backend/reports/jest-results.json)
          SKIPPED=$(jq '.numPendingTests' backend/reports/jest-results.json)
          echo "Tests: total=$TOTAL, passed=$PASSED, failed=$FAILED, skipped=$SKIPPED" >> "$LOG_PATH"
        else
          echo "Tests: (no backend/reports/jest-results.json found)" >> "$LOG_PATH"
        fi
        if [ -f "backend/coverage/coverage-summary.json" ]; then
          STMT=$(jq '.total.statements.pct' backend/coverage/coverage-summary.json)
          BRCH=$(jq '.total.branches.pct'   backend/coverage/coverage-summary.json)
          FUNC=$(jq '.total.functions.pct'  backend/coverage/coverage-summary.json)
          LNS=$(jq '.total.lines.pct'       backend/coverage/coverage-summary.json)
          echo "Coverage: statements=${STMT}%, branches=${BRCH}%, functions=${FUNC}%, lines=${LNS}%" >> "$LOG_PATH"
        else
          echo "Coverage: (no backend/coverage/coverage-summary.json found)" >> "$LOG_PATH"
        fi
        echo "" >> "$LOG_PATH"
        echo "Artifacts:" >> "$LOG_PATH"
        echo "- backend/reports/jest-results.json" >> "$LOG_PATH"
        echo "- backend/coverage/**" >> "$LOG_PATH"
        echo "" >> "$LOG_PATH"
        echo "Notes: Custom log generated by .github/actions/make-test-log." >> "$LOG_PATH"
        echo "log_path=$LOG_PATH" >> $GITHUB_OUTPUT
