name: Sanity - AWS creds
on:
  workflow_dispatch:
jobs:
  whoami:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}
      - name: Show caller identity (safe)
        run: aws sts get-caller-identity

      - name: Check S3 log bucket (safe, may be empty)
        env:
          LOG_BUCKET: ${{ secrets.LOG_BUCKET }}
        run: aws s3 ls "s3://$LOG_BUCKET" || true
